server:
  port: 9901

spring:
  application:
    name: STUDENT SERVICES
  datasource:
    url: jdbc:postgresql://localhost:10543/briix
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true